JWT_SECRET_KEY = 'S51S8ZCrGeAV72S'
mailjet_api_key = 'abcdefghijklmnopqrstuvwxyz'
mailjet_api_secret = 'abcdefghijklmnopqrstuvwxyz'
MAIL_PASSWORD = 'abcdefghijklmnopqrstuvwxyz'
DAILY_CHECK = 'abcdefghijklmnopqrstuvwxyz'
