fr = {
  'lang': 'fr',
  'calendar': 'Calendrier',
  'userTitle': 'Utilisateur',
  'email': 'Adresse email',
  'password': 'Mot de passe',
  'remember':'Se souvenir de moi',
  'login': 'Connexion',
  'gotaccount': "Pas encore de compte ?",
  'signup': "S'inscrire",
  'forgot': 'Mot de passe oublié ?',
  'login_error': 'La connexion a échoué',
  'register': "Inscription",
  'firstname': 'Prénom',
  'lastname': 'NOM',
  'gotohome': 'Retour accueil',
  'checkemail': 'OK, vérifie ton courriel !',
  'alreadyRegistered': 'Adresse email déjà enregistrée',
  'register_error': "L'inscription a échoué",
  'userSettings': 'Préférences',
  'phone': 'Téléphone',
  'share_email': "Partager l'<b>adresse email</b> avec les autres membres ?",
  'share_phone': 'Partager le <b>téléphone</b> avec les autres membres ?',
  'Identity': 'Identité',
  'changePassword': 'Modifier le mot de passe',
  'save': 'Enregistrer',
  'visibility': 'Partage',
  'themeLabel': 'Theme',
  'saved': 'Préférences sauvegardées !',
  'saved_error': "Erreur à l'enregistrement :-("
}
en = {
  'lang': 'fr',
  'calendar': 'Calendar',
  'userTitle': 'User',
  'email': 'Email address',
  'password': 'Password',
  'remember':'Remember me',
  'login': 'Login',
  'gotaccount': "Don't have an account?",
  'signup': "Sign up",
  'forgot': 'Forgot your password?',
  'login_error': 'Login attempt failed',
  'register': 'Register',
  'firstname': 'First name',
  'lastname': 'LAST NAME',
  'gotohome': 'Return to home page',
  'checkemail': 'OK, check your emails!',
  'alreadyRegistered': 'Email already registered',
  'register_error': 'Sign up failed',
  'userSettings': 'Settings',
  'phone': 'Phone',
  'share_email': 'Share email with other members?',
  'share_phone': 'Share phone with other members?',
  'Identity': 'Identity',
  'changePassword': 'Modify your password',
  'save': 'Save',
  'visibility': 'Sharing',
  'themeLabel': 'Theme',
  'saved': 'Settings saved!',
  'saved_error': "Error while saving :-("
}
