import settings
trads = {
 'fr': {
  'lang': 'fr',
  'calendar': 'Calendrier',
  'userTitle': 'Membre',
  'usersTitle': 'Les membres',
  'email': 'Adresse email',
  'password': 'Mot de passe',
  'remember':'Se souvenir de moi',
  'login': 'Connexion',
  'logout': 'Déconnexion',
  'gotaccount': "Pas encore de compte ?",
  'signup': "S'inscrire",
  'forgot': 'Mot de passe oublié ?',
  'login_error': 'La connexion a échoué',
  'register': "Inscription",
  'firstname': 'Prénom',
  'lastname': 'NOM',
  'gotohome': 'Retour calendrier',
  'checkemail': 'OK, vérifie ton courriel !',
  'alreadyRegistered': 'Adresse email déjà enregistrée',
  'register_error': "L'inscription a échoué",
  'userSettings': 'Préférences',
  'phone': 'Téléphone',
  'share_email': "Partager l'<b>adresse email</b> avec les autres membres ?",
  'share_phone': 'Partager le <b>téléphone</b> avec les autres membres ?',
  'Identity': 'Identité',
  'changePassword': 'Modifier le mot de passe',
  'save': 'Enregistrer',
  'visibility': 'Partage',
  'themeLabel': 'Thème',
  'saved': 'Préférences sauvegardées !',
  'saved_error': "Erreur à l'enregistrement :-(",
  'oldPassword': 'Ancien mot de passe',
  'newPassword': 'Nouveau mot de passe',
  'newPassword2': 'Nouveau mot de passe (encore)',
  'pwdMismatch': "Le nouveau mot de passe n'est pas le même dans les 2 champs",
  'pwdChanged': 'Mot de passe changé',
  'pwdChanged_error': 'Erreur lors du changement de mot de passe',
  'Avatar': 'Photo',
  'Remove_avatar': "Supprimer l'image",
  'Home': 'Calendrier',
  'Blog': 'Le blog',
  'type_email': "Rempli d'abord ton email",
  'default': 'par défaut',
  'Notifications': 'Notifications',
  'notif_new_event': 'Recevoir les emails de nouvelle sortie',
  'notif_event_change': "Recevoir les notifications email sur une sortie ou j'ai interagi",
  'notif_event_change_note': 'Note: Tu peux temporairement désactiver les notifications sur une sortie en cliquant sur la cloche',
  'notif_tomorrow_events': 'Recevoir les emails des sorties prévues pour demain',
  'has_whatsapp': "J'ai WhatsApp",
  'Me': 'Mon profil',
  'MyWing': 'Mon aile :',
  'TheWing': 'Son aile',
  'MyPresentation': 'Ma présentation : (type de pratique, expérience, qui suis-je, ...)',
  'rescue_title': 'Un incident est survenu',
  'APPROVE': 'APPROUVER',
  'DELETE': 'SUPPRIMER',
  'ChangeBackground': "Changer l'image"
 },
 'en': {
  'lang': 'en',
  'calendar': 'Calendar',
  'userTitle': 'Member',
  'usersTitle': 'Members',
  'email': 'Email address',
  'password': 'Password',
  'remember':'Remember me',
  'login': 'Login',
  'logout': 'Logout',
  'gotaccount': "Don't have an account?",
  'signup': "Sign up",
  'forgot': 'Forgot your password?',
  'login_error': 'Login attempt failed',
  'register': 'Register',
  'firstname': 'First name',
  'lastname': 'LAST NAME',
  'gotohome': 'Return to calendar',
  'checkemail': 'OK, check your emails!',
  'alreadyRegistered': 'Email already registered',
  'register_error': 'Sign up failed',
  'userSettings': 'Settings',
  'phone': 'Phone',
  'share_email': 'Share email with other members?',
  'share_phone': 'Share phone with other members?',
  'Identity': 'Identity',
  'changePassword': 'Modify your password',
  'save': 'Save',
  'visibility': 'Sharing',
  'themeLabel': 'Theme',
  'saved': 'Settings saved!',
  'saved_error': "Error while saving :-(",
  'oldPassword': 'Old password',
  'newPassword': 'New password',
  'newPassword2': 'New password (again)',
  'pwdMismatch': 'New password is different in the 2 fields',
  'pwdChanged': 'Password changed',
  'pwdChanged_error': 'Error while changing password',
  'Avatar': 'Picture',
  'Remove_avatar': 'Remove picture',
  'Home': 'Calendar',
  'Blog': 'Blog',
  'type_email': 'Type your email first',
  'default': 'default',
  'Notifications': 'Notifications',
  'notif_new_event': 'Receive email when a new event is added',
  'notif_event_change': "Receive email notifications on an event on which I interracted",
  'notif_event_change_note': 'Note: You can temporarily deactivate notifications about an event by clicking on the bell',
  'notif_tomorrow_events': 'Receive email for tomorrow events',
  'has_whatsapp': 'I have WhatsApp',
  'Me': 'Me',
  'MyWing': 'My wing:',
  'TheWing': 'His/her wing:',
  'MyPresentation': 'My presentation: (paragliding practice, experience, who am i, ...)',
  'rescue_title': 'Something wrong happened',
  'APPROVE': 'APPROVE',
  'DELETE': 'DELETE',
  'ChangeBackground': 'Change Background'
 }
}

lang = trads[settings.lang]

def i18n(key):
  return trads[settings.lang][key]
