---
name: Build and deploy app

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@main

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
      working-directory: ./front

    - name: Compile front
      run: npm run build
      working-directory: ./front
      env:
        NODE_ENV: production

    - name: Deploy on production via RSYNC
      uses: up9cloud/action-rsync@master
      env:
        KEY: ${{ secrets.SSHKEY }}
        USER: ${{ secrets.USERNAME }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        ARGS: -avzrF
        SOURCE: back/
        TARGET: /var/www/EventOrganizer/

    - name: Multiple commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/EventOrganizer
          source env313/bin/activate
          pip install -r requirements.txt
          find . -type d -name "__pycache__" -not -path "./env*/*" -exec rm -rf "{}" \;
          sudo systemctl restart eventorganizer

    - name: Zip artifact
      run: |
        cd back;
        zip -r ../artifact.zip *

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Release ${{ github.ref_name }}
        body_path: last_release.md
        token: ${{ secrets.GITHUB_TOKEN }}
        files: artifact.zip
